stomp:
  stomplets:
    irc_stomplet:
      class: IrcStomplet
      route: '/stomplet/irc'
      config:
        destination: /queue/irc_messages

services:
  irc-bot:
    service: IrcBotService
    singleton: true
    config:
      nick: torquebox_bot
      server: irc.freenode.net
      port: 6667
      channel: '#torquebox'
      destination: /queue/irc_messages

queues:
  /queue/irc_messages:
    durable: false

